name: Docker Image CI

on:
 workflow_dispatch:
 push:
  branches: [ master ]
 pull_request:
  branches: [ master ]
jobs:
 build-docker:
  runs-on: ubuntu-latest
  env:
    MICRO_SERVICE_VERSION: "3.0"
  
  steps:
  - name: Checkout sources
    uses: actions/checkout@v2
  - name: Build the Docker image
    run: docker build . --file Dockerfile --tag docker.io/aliciane-pinault/archi-micro-serv:${{ env.MICRO_SERVICE_VERSION }}-${GITHUB_RUN_NUMBER}
